stages:
  download_and_extract:
    cmd: python download_data.py
    deps:
      - download_data.py
    params:
      - images_dir
      - labels_dir
      - labels_url
      - images_url
    outs:
      - "${images_dir}"
      - "${labels_dir}"

  process_data:
    cmd: python process_data.py
    deps:
      - "${images_dir}"
      - "${labels_dir}"
      - process_data.py
    outs:
      - "${train_split_path}"
      - "${val_split_path}"
      - "${test_split_path}"
    params:
      - train_split_path
      - val_split_path
      - test_split_path
      - random_state
      - test_size
      - val_size
      - n_batches
      - batch_names_select

  train:
    cmd: python train.py
    deps:
      - "${train_split_path}"
      - "${val_split_path}"
      - train.py
    params:
      - model_save_path
      - lr
    outs:
      - "${model_save_path}"

  test:
    cmd: python test.py
    deps:
      - "${model_save_path}"
      - "${test_split_path}"
      - test.py
    params:
      - model_save_path